const MSG = {
  DB_CONNECTED: 'Database connected successfully',

  AUTH: {
    SELF: 'SELF',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    USER_UPDATED_FULL_NAME: 'USER_UPDATED_FULL_NAME',
    USER_UPDATED_AVATAR: 'USER_UPDATED_AVATAR',
  },

  TOOL_CALLING: {
    USE_TOOL_CALLING: 'USE_TOOL_CALLING',
  },

  AI_CONVERSATION: {
    CREATE_AI_CONVERSATION: 'CREATE_AI_CONVERSATION',
  },
}

export default MSG
