const MSG = {
  DB_CONNECTED: 'Database connected successfully',

  AUTH: {
    SELF: 'SELF',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_VERIFIED: 'USER_VERIFIED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    RESET_PASSWORD: 'RESET_PASSWORD',
    USER_UPDATED_FULL_NAME: 'USER_UPDATED_FULL_NAME',
    USER_UPDATED_AVATAR: 'USER_UPDATED_AVATAR',
  },

  CHAT_BOT: {
    GET_CHAT_BOTS: 'GET_CHAT_BOTS',
    GET_CHAT_BOT: 'GET_CHAT_BOT',
    DELET_CHAT_BOT: 'DELETE_CHAT_BOT',
  },
}

export default MSG
