import { config } from 'dotenv'
config()

const {
  PORT,
  DB_URL,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  SESSION_SECRET_KEY,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  FRONTEND_URL,
  MAIL_PORT,
  MAIL_HOST,
  MAIL_PASSWORD,
  MAIL_FROM,
  MAIL_USERNAME,
  CLOUD_NAME,
  CLOUD_API_KEY,
  CLOUD_API_SECRET,
  LOGO,
  BACKEND_URL,
  PROJECT_NAME,
} = process.env

const ENV = {
  PORT,
  DB_URL,
  NODE_ENV,
  ACCESS_TOKEN_SECRET,
  SESSION_SECRET_KEY,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_CLIENT_ID,
  FRONTEND_URL,
  MAIL_PORT,
  MAIL_HOST,
  MAIL_PASSWORD,
  MAIL_FROM,
  MAIL_USERNAME,
  CLOUD_NAME,
  CLOUD_API_KEY,
  CLOUD_API_SECRET,
  LOGO,
  BACKEND_URL,
  PROJECT_NAME,
}

export default ENV
